exports.seed = function(knex, Promise) {
  return knex('dishes').del()
    .then(function () {
      return Promise.all([
        knex('dishes').insert({id: 1, price: "14.99", time_to_done: "15", name: 'Peperoni', description: 'Peperoni',photo: 'https://www.nestleprofessional.us/sites/g/files/gfb131/f/styles/recipe/public/media/honey-citrus-chicken-minors-nestle-professional-food-service-recipe-540x400.jpg?itok=O987jk8X', restaurants_id: 1}),
        knex('dishes').insert({id: 2, price: "21.99", time_to_done: "20", name: 'California Rolls', description: 'California Rolls', photo: 'https://qandme.net/images/report97.png', restaurants_id: 2}),
        knex('dishes').insert({id: 3, price: "5.99", time_to_done: "12", name: '8OZ Hamburguer', description: '8OZ Hamburguer', photo: 'https://themunchandtattle.files.wordpress.com/2014/12/20140918-jamie-olivers-comfort-food-insanity-burger-david-loftus.jpg', restaurants_id: 3}),
        knex('dishes').insert({id: 4, price: "41.99", time_to_done: "15", name: 'Peperoni pizza', description: 'Peperoni pizza', photo: 'https://www.nestleprofessional.us/sites/g/files/gfb131/f/styles/recipe/public/media/red-curry-samosa-maggi-nestle-professional-food-service-recipe-540x400.jpg?itok=xCbiTWCh', restaurants_id: 1}),
        knex('dishes').insert({id: 5, price: "15.99", time_to_done: "20", name: 'Teriyaki Soy', description: 'Teriyaki Soy', photo: 'https://www.nestleprofessional.co.uk/sites/g/files/gfb191/f/styles/recipe/public/media/5.1-tuna-sweetcorn-ciabatta-pizza.jpg?itok=mxmWlXA8', restaurants_id: 2}),
        knex('dishes').insert({id: 6, price: "16.99", time_to_done: "15", name: 'Hamburguer', description: 'Hamburguer', photo: 'https://www.nestleprofessional.us/sites/g/files/gfb131/f/styles/recipe/public/media/old-fashioned-chicken-noodle-soup-made-with-minors-chicken-base-food-service-recipe-540x400.jpg?itok=UuFwEFlh', restaurants_id: 3}),
        knex('dishes').insert({id: 7, price: "25.99", time_to_done: "30", name: 'Atlantic Salmon', description: 'Atlantic Salmon', photo: 'https://www.nestleprofessional.us/sites/g/files/gfb131/f/styles/recipe/public/media/salmon-plus-side-dish-assortment-minors-stouffers-nestle-pro-food-service-recipe-540x400.jpg?itok=lyzQvIaT', restaurants_id: 1}),
        knex('dishes').insert({id: 8, price: "11.99", time_to_done: "25", name: 'Tofu', description: 'Tofu', photo: 'https://www.nestleprofessional.us/sites/g/files/gfb131/f/styles/recipe/public/media/spicy-tofu-skin-salad-maggi-nestle-professional-food-service-recipe-540x400.jpg?itok=EP8RBdNl', restaurants_id: 2}),
        knex('dishes').insert({id: 9, price: "33.99", time_to_done: "30", name: 'Striploin', description: 'Striploin', photo: 'https://www.nestleprofessional.us/sites/g/files/gfb131/f/styles/recipe/public/media/beefy-roasted-steak-potatoes-gluten-free-minors-nestle-professional-food-service-recipe-540x400.jpg?itok=652ZCHdN', restaurants_id: 3}),
        knex('dishes').insert({id: 10, price: "41.99", time_to_done: "24", name: 'Beef chilli', description: 'Beef chilli', photo: 'https://www.nestleprofessional.us/sites/g/files/gfb131/f/styles/recipe/public/media/nachos-with-chef-mate-que-bueno-nacho-cheese-sauce-nestle-pro-food-service-recipe-540x400.jpg?itok=Te7jHSJF', restaurants_id: 1}),
        knex('dishes').insert({id: 11, price: "15.99", time_to_done: "25", name: 'Fried Rice', description: 'Fried Rice', photo: 'https://www.nestleprofessional.us/sites/g/files/gfb131/f/styles/recipe/public/media/quinoa-salad-spicy-pumpkin-vinaigrette-libbys-nestle-professional-food-service-recipe-540x400.jpg?itok=unP9tICk', restaurants_id: 2}),
        knex('dishes').insert({id: 12, price: "11.99", time_to_done: "30", name: 'Nachos and Cheese', description: 'Nachos and Cheese', photo: 'https://www.nestleprofessional.us/sites/g/files/gfb131/f/styles/recipe/public/media/young-jackfruit-stir-fry-maggi-nestle-professional-food-service-recipe-540x400.jpg?itok=36eTdMJb', restaurants_id: 3})
      ]);
    });
};
